#############################################################################
# Makefile for building: MaplelegendsBossHelper
# Generated by qmake (3.1) (Qt 6.9.1)
# Project:  MaplelegendsBossHelper.pro
# Template: app
# Command: /home/quinaz/qt6-host/bin/qmake6 -o Makefile MaplelegendsBossHelper.pro -qtconf /home/quinaz/qt6-win-static/bin/target_qt.conf CONFIG+=static
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = /home/quinaz/qt6-host/bin/qmake6
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/quinaz/qt6-host/bin/qmake6 -install qinstall
QINSTALL_PROGRAM = /home/quinaz/qt6-host/bin/qmake6 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
IDC           = idc
IDL           = midl
ZIP           = 
DEF_FILE      = 
RES_FILE      = 
SED           = sed
MOVE          = mv -f
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: MaplelegendsBossHelper.pro ../../../qt6-win-static/mkspecs/win32-g++/qmake.conf ../../../qt6-win-static/mkspecs/features/spec_pre.prf \
		../../../qt6-win-static/mkspecs/qdevice.pri \
		../../../qt6-win-static/mkspecs/features/device_config.prf \
		../../../qt6-win-static/mkspecs/common/sanitize.conf \
		../../../qt6-win-static/mkspecs/common/gcc-base.conf \
		../../../qt6-win-static/mkspecs/common/g++-base.conf \
		../../../qt6-win-static/mkspecs/features/win32/windows_vulkan_sdk.prf \
		../../../qt6-win-static/mkspecs/common/windows-vulkan.conf \
		../../../qt6-win-static/mkspecs/common/g++-win32.conf \
		../../../qt6-win-static/mkspecs/common/windows-desktop.conf \
		../../../qt6-win-static/mkspecs/qconfig.pri \
		../../../qt6-win-static/mkspecs/modules/qt_ext_freetype.pri \
		../../../qt6-win-static/mkspecs/modules/qt_ext_libjpeg.pri \
		../../../qt6-win-static/mkspecs/modules/qt_ext_libpng.pri \
		../../../qt6-win-static/mkspecs/modules/qt_lib_concurrent.pri \
		../../../qt6-win-static/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../qt6-win-static/mkspecs/modules/qt_lib_core.pri \
		../../../qt6-win-static/mkspecs/modules/qt_lib_core_private.pri \
		../../../qt6-win-static/mkspecs/modules/qt_lib_dbus.pri \
		../../../qt6-win-static/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../qt6-win-static/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../qt6-win-static/mkspecs/modules/qt_lib_entrypoint_private.pri \
		../../../qt6-win-static/mkspecs/modules/qt_lib_example_icons_private.pri \
		../../../qt6-win-static/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri \
		../../../qt6-win-static/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../qt6-win-static/mkspecs/modules/qt_lib_freetype_private.pri \
		../../../qt6-win-static/mkspecs/modules/qt_lib_gui.pri \
		../../../qt6-win-static/mkspecs/modules/qt_lib_gui_private.pri \
		../../../qt6-win-static/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../../../qt6-win-static/mkspecs/modules/qt_lib_jpeg_private.pri \
		../../../qt6-win-static/mkspecs/modules/qt_lib_network.pri \
		../../../qt6-win-static/mkspecs/modules/qt_lib_network_private.pri \
		../../../qt6-win-static/mkspecs/modules/qt_lib_opengl.pri \
		../../../qt6-win-static/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../qt6-win-static/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../../qt6-win-static/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../../qt6-win-static/mkspecs/modules/qt_lib_png_private.pri \
		../../../qt6-win-static/mkspecs/modules/qt_lib_printsupport.pri \
		../../../qt6-win-static/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../qt6-win-static/mkspecs/modules/qt_lib_sql.pri \
		../../../qt6-win-static/mkspecs/modules/qt_lib_sql_private.pri \
		../../../qt6-win-static/mkspecs/modules/qt_lib_testinternals_private.pri \
		../../../qt6-win-static/mkspecs/modules/qt_lib_testlib.pri \
		../../../qt6-win-static/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../qt6-win-static/mkspecs/modules/qt_lib_widgets.pri \
		../../../qt6-win-static/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../qt6-win-static/mkspecs/modules/qt_lib_xml.pri \
		../../../qt6-win-static/mkspecs/modules/qt_lib_xml_private.pri \
		../../../qt6-win-static/mkspecs/modules/qt_lib_zlib_private.pri \
		../../../qt6-win-static/mkspecs/features/qt_functions.prf \
		../../../qt6-win-static/mkspecs/features/qt_config.prf \
		../../../qt6-win-static/mkspecs/win32-g++/qmake.conf \
		../../../qt6-win-static/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../qt6-win-static/mkspecs/features/exclusive_builds.prf \
		../../../qt6-win-static/mkspecs/features/toolchain.prf \
		../../../qt6-win-static/mkspecs/features/default_pre.prf \
		../../../qt6-win-static/mkspecs/features/win32/default_pre.prf \
		../../../qt6-win-static/mkspecs/features/resolve_config.prf \
		../../../qt6-win-static/mkspecs/features/exclusive_builds_post.prf \
		../../../qt6-win-static/mkspecs/features/default_post.prf \
		../../../qt6-win-static/mkspecs/features/precompile_header.prf \
		../../../qt6-win-static/mkspecs/features/warn_on.prf \
		../../../qt6-win-static/mkspecs/features/permissions.prf \
		../../../qt6-win-static/mkspecs/features/qt.prf \
		../../../qt6-win-static/mkspecs/features/resources_functions.prf \
		../../../qt6-win-static/mkspecs/features/resources.prf \
		../../../qt6-win-static/mkspecs/features/moc.prf \
		../../../qt6-win-static/mkspecs/features/win32/opengl.prf \
		../../../qt6-win-static/mkspecs/features/uic.prf \
		../../../qt6-win-static/mkspecs/features/qmake_use.prf \
		../../../qt6-win-static/mkspecs/features/file_copies.prf \
		../../../qt6-win-static/mkspecs/features/win32/windows.prf \
		../../../qt6-win-static/mkspecs/features/testcase_targets.prf \
		../../../qt6-win-static/mkspecs/features/exceptions.prf \
		../../../qt6-win-static/mkspecs/features/yacc.prf \
		../../../qt6-win-static/mkspecs/features/lex.prf \
		MaplelegendsBossHelper.pro \
		../../../qt6-win-static/lib/Qt6Widgets.prl \
		../../../qt6-win-static/lib/Qt6Gui.prl \
		../../../qt6-win-static/lib/Qt6Core.prl \
		../../../qt6-win-static/lib/Qt6EntryPoint.prl \
		../../../qt6-win-static/mkspecs/features/build_pass.prf \
		img.qrc
	$(QMAKE) -o Makefile MaplelegendsBossHelper.pro -qtconf /home/quinaz/qt6-win-static/bin/target_qt.conf CONFIG+=static
../../../qt6-win-static/mkspecs/features/spec_pre.prf:
../../../qt6-win-static/mkspecs/qdevice.pri:
../../../qt6-win-static/mkspecs/features/device_config.prf:
../../../qt6-win-static/mkspecs/common/sanitize.conf:
../../../qt6-win-static/mkspecs/common/gcc-base.conf:
../../../qt6-win-static/mkspecs/common/g++-base.conf:
../../../qt6-win-static/mkspecs/features/win32/windows_vulkan_sdk.prf:
../../../qt6-win-static/mkspecs/common/windows-vulkan.conf:
../../../qt6-win-static/mkspecs/common/g++-win32.conf:
../../../qt6-win-static/mkspecs/common/windows-desktop.conf:
../../../qt6-win-static/mkspecs/qconfig.pri:
../../../qt6-win-static/mkspecs/modules/qt_ext_freetype.pri:
../../../qt6-win-static/mkspecs/modules/qt_ext_libjpeg.pri:
../../../qt6-win-static/mkspecs/modules/qt_ext_libpng.pri:
../../../qt6-win-static/mkspecs/modules/qt_lib_concurrent.pri:
../../../qt6-win-static/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../qt6-win-static/mkspecs/modules/qt_lib_core.pri:
../../../qt6-win-static/mkspecs/modules/qt_lib_core_private.pri:
../../../qt6-win-static/mkspecs/modules/qt_lib_dbus.pri:
../../../qt6-win-static/mkspecs/modules/qt_lib_dbus_private.pri:
../../../qt6-win-static/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../qt6-win-static/mkspecs/modules/qt_lib_entrypoint_private.pri:
../../../qt6-win-static/mkspecs/modules/qt_lib_example_icons_private.pri:
../../../qt6-win-static/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri:
../../../qt6-win-static/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../qt6-win-static/mkspecs/modules/qt_lib_freetype_private.pri:
../../../qt6-win-static/mkspecs/modules/qt_lib_gui.pri:
../../../qt6-win-static/mkspecs/modules/qt_lib_gui_private.pri:
../../../qt6-win-static/mkspecs/modules/qt_lib_harfbuzz_private.pri:
../../../qt6-win-static/mkspecs/modules/qt_lib_jpeg_private.pri:
../../../qt6-win-static/mkspecs/modules/qt_lib_network.pri:
../../../qt6-win-static/mkspecs/modules/qt_lib_network_private.pri:
../../../qt6-win-static/mkspecs/modules/qt_lib_opengl.pri:
../../../qt6-win-static/mkspecs/modules/qt_lib_opengl_private.pri:
../../../qt6-win-static/mkspecs/modules/qt_lib_openglwidgets.pri:
../../../qt6-win-static/mkspecs/modules/qt_lib_openglwidgets_private.pri:
../../../qt6-win-static/mkspecs/modules/qt_lib_png_private.pri:
../../../qt6-win-static/mkspecs/modules/qt_lib_printsupport.pri:
../../../qt6-win-static/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../qt6-win-static/mkspecs/modules/qt_lib_sql.pri:
../../../qt6-win-static/mkspecs/modules/qt_lib_sql_private.pri:
../../../qt6-win-static/mkspecs/modules/qt_lib_testinternals_private.pri:
../../../qt6-win-static/mkspecs/modules/qt_lib_testlib.pri:
../../../qt6-win-static/mkspecs/modules/qt_lib_testlib_private.pri:
../../../qt6-win-static/mkspecs/modules/qt_lib_widgets.pri:
../../../qt6-win-static/mkspecs/modules/qt_lib_widgets_private.pri:
../../../qt6-win-static/mkspecs/modules/qt_lib_xml.pri:
../../../qt6-win-static/mkspecs/modules/qt_lib_xml_private.pri:
../../../qt6-win-static/mkspecs/modules/qt_lib_zlib_private.pri:
../../../qt6-win-static/mkspecs/features/qt_functions.prf:
../../../qt6-win-static/mkspecs/features/qt_config.prf:
../../../qt6-win-static/mkspecs/win32-g++/qmake.conf:
../../../qt6-win-static/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../qt6-win-static/mkspecs/features/exclusive_builds.prf:
../../../qt6-win-static/mkspecs/features/toolchain.prf:
../../../qt6-win-static/mkspecs/features/default_pre.prf:
../../../qt6-win-static/mkspecs/features/win32/default_pre.prf:
../../../qt6-win-static/mkspecs/features/resolve_config.prf:
../../../qt6-win-static/mkspecs/features/exclusive_builds_post.prf:
../../../qt6-win-static/mkspecs/features/default_post.prf:
../../../qt6-win-static/mkspecs/features/precompile_header.prf:
../../../qt6-win-static/mkspecs/features/warn_on.prf:
../../../qt6-win-static/mkspecs/features/permissions.prf:
../../../qt6-win-static/mkspecs/features/qt.prf:
../../../qt6-win-static/mkspecs/features/resources_functions.prf:
../../../qt6-win-static/mkspecs/features/resources.prf:
../../../qt6-win-static/mkspecs/features/moc.prf:
../../../qt6-win-static/mkspecs/features/win32/opengl.prf:
../../../qt6-win-static/mkspecs/features/uic.prf:
../../../qt6-win-static/mkspecs/features/qmake_use.prf:
../../../qt6-win-static/mkspecs/features/file_copies.prf:
../../../qt6-win-static/mkspecs/features/win32/windows.prf:
../../../qt6-win-static/mkspecs/features/testcase_targets.prf:
../../../qt6-win-static/mkspecs/features/exceptions.prf:
../../../qt6-win-static/mkspecs/features/yacc.prf:
../../../qt6-win-static/mkspecs/features/lex.prf:
MaplelegendsBossHelper.pro:
../../../qt6-win-static/lib/Qt6Widgets.prl:
../../../qt6-win-static/lib/Qt6Gui.prl:
../../../qt6-win-static/lib/Qt6Core.prl:
../../../qt6-win-static/lib/Qt6EntryPoint.prl:
../../../qt6-win-static/mkspecs/features/build_pass.prf:
img.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile MaplelegendsBossHelper.pro -qtconf /home/quinaz/qt6-win-static/bin/target_qt.conf CONFIG+=static

qmake_all: FORCE

make_first: release-make_first debug-make_first  FORCE
all: release-all debug-all  FORCE
clean: release-clean debug-clean  FORCE
distclean: release-distclean debug-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash

release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first

benchmark: first
FORCE:

.SUFFIXES:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
